### ISSUE TITLE
`IdentityManager::removeOwner()` and `MetaIdentityManager::removeOwner()` may be called on oneself

### ISSUE THREAD

**Issue by jessicagmarshall** [uport-project/uport-identity#78]
https://github.com/uport-project/uport-identity/blob/880f8b81b9355edfe62c35817562b24e90513d2a/contracts/IdentityManager.sol#L128-L132

* [IdentityManager::removeOwner()](https://github.com/uport-project/uport-identity/blob/880f8b81b9355edfe62c35817562b24e90513d2a/contracts/IdentityManager.sol#L128-L129)

As either `removeOwner()` function is written, an older owner has the ability to remove oneself as an owner. This functionality increases the likelihood that an owner accidentally deletes itself.

**Recommendation**

Add `require()` statement in both functions that ensures that `removeOwner()` cannot be called on oneself.

**Comment by naterush** [comment]
Is it possible there is some situation where an owner wants to remove themselves? Consider the following situation.

There are two owner keys. The first one performed some command (say, removing a different owner key) and thus is currently cooling down. The second one is compromised - in the sense that some adversary gets control of the key as well. If the user cannot use the owner key to remove itself, then the adversary has more time to delete the other currently-frozen owner key.

It seems to me this is something we want to enforce on a UX level, rather than in the contracts, based on situations like the above (though it is totally contrived).

**Comment by oed** [comment]
So if it is enforced in the UX level how would a normal user ever get the chance to preform the action you are describing? It is a valid point, but I don't think it will ever be used like that.

**Comment by naterush** [comment]
Enforced at a UX level meaning "You are about to remove this key. This is very unusual behavior that you should probably not do unless this key is compromised"

They can in the worst case, but generally don't. It seems more flexible to enforce this off-chain to me.

**Comment by oed** [comment]
I see your point (and if the app was built for me I would agree) but I'm unsure if users should even know about keys. 
Maybe something like `You are about to remove this device. This is a very unusual behaviour that you should not do unless ...`
But since the keys should idealy live in the secure enclave I have a hard time seeing this happening.
